### ISSUE TITLE
Follows directory symlinks when decompressing, allowing arbitrary file overwrite in certain (contrived) scenarios

### ISSUE THREAD

**Issue by Shnatsel** [quininer/unzipx#3]
Steps to reproduce on Unix:

```bash
mkdir ../should_be_empty
mkdir compressed-dir
ln -s $(realpath ../should_be_empty) compressed-dir/nested_folder
unzipx compressed-dir.zip
```

The file to decompress: [compressed-dir.zip](https://github.com/quininer/unzipx/files/10948771/compressed-dir.zip)

You can see that the `should_be_empty` directory outside the path where decompression takes place gets a file in it. This is a security issue in certain contrived scenarios - for example, if the `unzipx` process is setuid or running with privileges higher than the current user has, the user can craft ZIP files that overwrite files he doesn't have access to normally, potentially allowing privilege escalation.

Note that checking if something is a symlink is insufficient because it can be bypassed via race conditions - the Rust standard library had this vulnerability: https://github.com/rust-lang/rust/security/advisories/GHSA-r9cc-f5pr-p3j2

**Comment by Shnatsel** [comment]
It seems the regular `unzip` does this as well, not just `unzipx`.

**Comment by quininer** [comment]
I'm not sure this is a vulnerability, which seems fairly consistent with user expectations.

I occasionally do something similar, like a symbolic link to a dot dir, for convenient syncing of config files.

If this is a vulnerability, then vulnerability should be in setuid. this is because unzip action will obviously write files to directory. You can configure setuid for any program that has the --output capability to do this.

**Comment by Shnatsel** [comment]
Since this matches the current behavior of `unzip`, I'm going to assume this is intended behavior and close this. Thanks for your consideration!
